IK_Project.UI/Models/UpdatePasswordViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace IK_Project.UI.Models
{
    public class UpdatePasswordViewModel
    {
        [Required(ErrorMessage = "New Password is Required.")]
        [DataType(DataType.Password)]
        [Display(Name = "New Password")]
        [RegularExpression(@"^(?=.*\d)(?=.*[A-Z])(?=.*\W).{8,}$", ErrorMessage = "Your password must contain at least one uppercase letter, one special character, one digit, and be at least 8 characters long.")]

        public string NewPassword { get; set; }

        [DataType(DataType.Password)]
        [Display(Name = "Confirm Password")]
        [Compare("NewPassword", ErrorMessage = "The new password and password confirmation do not match.")]
        public string ConfirmPassword { get; set; }
    }
}

IK_Project.UI/Areas/Admin/Controllers/CompanyController.cs
using AutoMapper;
using Humanizer;
using IK_Project.Application.Models.DTOs.CompanyDTOs;
using IK_Project.Application.Models.DTOs.CompanyManagerDTOs;
using IK_Project.Application.Services.CompanyService;
using IK_Project.Application.Services.MenuService;
using IK_Project.Domain.Entities.Concrete;
using IK_Project.Domain.Enums;
using IK_Project.Domain.Utilities.Interfaces;
using IK_Project.UI.Areas.Admin.Models.ViewModels.CompanyManagerVMs;
using IK_Project.UI.Areas.Admin.Models.ViewModels.CompanyVM;
using IK_Project.UI.FluentValidations.AdminAreaValidator.CompanyValidator;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System.Data;

namespace IK_Project.UI.Areas.Admin.Controllers
{

    public class CompanyController : AdminBaseController
    {
        private readonly ICompanyService _companyService;
        private readonly IMapper _mapper;
        //private readonly IAppUserService _appUserService;
        IWebHostEnvironment _webHostEnvironment;
        private readonly IMenuService _menuService;

        public CompanyController(ICompanyService companyService, IMapper mapper, IWebHostEnvironment webHostEnvironment, IMenuService menuService)
        {
            _companyService = companyService;
            _mapper = mapper;
            _webHostEnvironment = webHostEnvironment;
            _menuService = menuService;

        }

        public IActionResult Index()
        {
            return View();
        }


        //Aktif ve Aktif olmayan Company Listeleme
        public async Task<IActionResult> GetAllActiveAndDeactiveCompanies()
        {
            var result = await _companyService.GetDefaults(x => x.IsActive == true || x.IsActive == false);
            if (result.Data == null)
            {
                return View();
            }
            var listVM = _mapper.Map<List<AdminCompanyListVM>>(result.Data);

            return View(listVM);
        }
        public async Task<IActionResult> GetAllCompanies()
        {
            var result = await _companyService.AllCompanies();
            if (result.Data==null)
            {
                return View();
            }
            List<AdminCompanyListVM> companyList = _mapper.Map<List<AdminCompanyListVM>>(result.Data);
            return View(companyList);


        }

        //Company Ekleme
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            AdminCompanyCreateVM createVm = new AdminCompanyCreateVM()
            {
                MenuList = await GetMenuSelectListAsync(),
            };

            return View(createVm);

        }

        [HttpPost]
        public async Task<IActionResult> Create(AdminCompanyCreateVM vm)
        {
            if (ModelState.IsValid)
            {
                var menu = await _menuService.GetById(vm.MenuId);
                vm.DealEndDate = vm.DealStartDate.AddMonths(menu.Data.Period);
                var dto = _mapper.Map<CompanyCreateDTO>(vm);
                if (vm.LogoFile != null)
                {
                    string savedFilePath = await vm.LogoFile.SaveFileAsync(_webHostEnvironment.WebRootPath, "images");
                    dto.Logo = savedFilePath;
                }
                var result = await _companyService.Create(dto);
                if (result.IsSuccess)
                {
                    return RedirectToAction("GetAllCompanies");

                }


            }
            vm.MenuList = await GetMenuSelectListAsync();

            return View(vm);
        }
        

        //Toggle Active DeActive
        //[HttpGet]
        //public async Task<IActionResult> ActiveDeActive(int id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }
        //    else
        //    {
        //        CompanyUpdateVM company = _mapper.Map<CompanyUpdateVM>(await _companyService.GetById(id));

        //        return View(ActiveDeActive(company));
        //    }
        //}
        //[HttpPost]
        //public async Task<IActionResult> ActiveDeActive(CompanyUpdateVM vm)
        //{

        //    try
        //    {
        //        var editDto = _mapper.Map<CompanyUpdateDTO>(vm);
        //        await _companyService.Edit(editDto);
        //        return RedirectToAction("GetAllActiveAndDeactiveCompanies");
        //    }
        //    catch (Exception ex)
        //    {
        //        TempData["error"] = ex.Message;
        //        return RedirectToAction("GetAllActiveAndDeactiveCompanies");
        //    }
        //}

        //Delete
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                await _companyService.Remove(id);
                return RedirectToAction("GetAllCompanies");
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return RedirectToAction("GetAllCompanies");
            }
        }

        //  Category/Details/

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                var companyDto = await _companyService.GetById(id);
                AdminCompanyUpdateVM company = _mapper.Map<AdminCompanyUpdateVM>(companyDto.Data);
                company.MenuList = await GetMenuSelectListAsync();

                return View(company);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Details(AdminCompanyUpdateVM vm)
        {
            if (!ModelState.IsValid)
            {
                vm.MenuList = await GetMenuSelectListAsync();

                return View(vm);

            }
            
            var menu = await _menuService.GetById(vm.MenuId);
            vm.DealEndDate = vm.DealStartDate.AddMonths(menu.Data.Period);
            var editDto = _mapper.Map<CompanyUpdateDTO>(vm);
            if (vm.LogoFile != null)
            {
              
                string savedFilePath = await vm.LogoFile.SaveFileAsync(_webHostEnvironment.WebRootPath, "images");

                editDto.Logo = savedFilePath;
            }
            await _companyService.Edit(editDto);
            return RedirectToAction("GetAllCompanies");
        }

        private async Task<SelectList> GetMenuSelectListAsync()
        {
            var menus = await _menuService.AllMenus();
            if (menus.Data != null)
            {
                return new SelectList(menus.Data.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name,
                }), "Value", "Text");
            }
            else
            {
                // menus.Data null ise uygun bir SelectList oluşturun veya hata işleme stratejisi uygulayın.
                return new SelectList(Enumerable.Empty<SelectListItem>()); // Varsayılan boş SelectList örneği
            }

        }
        [HttpPost]
        public async Task<IActionResult> UpdateCompanyStatus(Guid companyId, bool newStatus)
        {

            var companyupdatedto = await _companyService.GetById(companyId);

            //companyupdatedto.Data.IsActive = newStatus;

            await _companyService.EditToggle(companyupdatedto.Data, newStatus);
            return View();
        }


    }
}

IK_Project.UI/Areas/Admin/Controllers/MenuController.cs
using AutoMapper;
using IK_Project.Application.Models.DTOs.AppRoleDTOs;
using IK_Project.Application.Models.DTOs.MenuDTOs;
using IK_Project.Application.Services.MenuService;
using IK_Project.Domain.Enums;
using IK_Project.UI.Areas.Admin.Models.ViewModels.MenuVMs;
using IK_Project.UI.Areas.Admin.Models.ViewModels.RoleVMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Data;

namespace IK_Project.UI.Areas.Admin.Controllers
{

    public class MenuController : AdminBaseController
    {

        private readonly IMenuService _menuService;
        private readonly IMapper _mapper;

        public MenuController(IMenuService menuService, IMapper mapper)
        {
            _menuService = menuService;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> GetAllMenus()
        {
            var listDTO = await _menuService.AllMenus();
            var listVM = _mapper.Map<List<AdminMenuListVM>>(listDTO.Data);

            return View(listVM);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(AdminMenuCreateVM vm)
        {
            if (ModelState.IsValid)
            {

                try
                {
                    var dto = _mapper.Map<MenuCreateDTO>(vm);
                    await _menuService.Create(dto);
                    return RedirectToAction("GetAllMenus");
                }
                catch (Exception ex)
                {
                    TempData["error"] = ex.Message;
                }

            }
            return View(vm);
        }


        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                await _menuService.Remove(id);
                return RedirectToAction("GetAllMenus");
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return RedirectToAction("GetAllMenus");

            }

        }

        [HttpGet]
        public async Task<IActionResult> Edit(Guid id)
        {
            var updateDto = await _menuService.GetById(id);
            var updateVm = _mapper.Map<AdminMenuUpdateVM>(updateDto.Data);

            return View(updateVm);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(AdminMenuUpdateVM vm)
        {

            if (ModelState.IsValid)
            {
                try
                {
                    var updateDto = _mapper.Map<MenuUpdateDTO>(vm);
                    await _menuService.Edit(updateDto);
                    return RedirectToAction("GetAllMenus");
                }
                catch (Exception ex)
                {

                    TempData["error"] = ex.Message;
                }
            }

            return View(vm);
        }
        [HttpPost]

        public async Task<IActionResult> UpdateMenuStatus(Guid menuId, bool newStatus)
        {

            var menuUpdateDto = await _menuService.GetById(menuId);
          
            await _menuService.EditToggle(menuUpdateDto.Data, newStatus);
            return View();

        }


    }
}

IK_Project.UI/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using IK_Project.UI.Models;
using IK_Project.Application.Services.MenuService;
using AutoMapper;
using IK_Project.UI.Areas.Admin.Models.ViewModels.MenuVMs;
using IK_Project.Application.Models.DTOs.AdminDTOs;
using IK_Project.UI.Areas.Admin.Models.ViewModels.AdminVM;
using IK_Project.Application.Models.DTOs.AppUserDTOs;
using IK_Project.Application.Services.AppUserService;

namespace IK_Project.UI.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;
    private readonly IMenuService _menuService;
    private readonly IMapper _mapper;
    private readonly IAppUserService _appUserService;


    public HomeController(ILogger<HomeController> logger, IMenuService menuService, IMapper mapper, IAppUserService appUserService)
    {
        _logger = logger;
        _menuService = menuService;
        _mapper = mapper;
        _appUserService = appUserService;
    }

    public async Task<IActionResult> Index()
    {
        //var listDTO = await _menuService.GetDefaults(x => x.IsActive == true);
        //var menuList = _mapper.Map<List<AdminMenuListVM>>(listDTO.Data);
        //return View(menuList);
        //return RedirectToAction("Create", "Admin", new { area = "Admin" });
        //return View();
        // return RedirectToAction("Index", "Home");
        //return RedirectToAction("Login", "Account");
        var listDTO = await _menuService.GetDefaults(x => x.IsActive == true);

        var combinedViewModel = new IndexCombineViewModel
        {
            UserInformation = new AppUserInformationVM(),
            //MenuList = new List<AdminMenuListVM>(),
            MenuList = _mapper.Map<List<AdminMenuListVM>>(listDTO.Data),// ListViewModel'i doldurun

        };

        return View(combinedViewModel);
    }
    public async Task<IActionResult> Create()
    {
        return View();
    }

    [HttpPost]
    public async Task<IActionResult> Create(IndexCombineViewModel model)
    {
        if (!ModelState.IsValid)
        {
            return View(model);
        }
      
        var appUserInformationDto = _mapper.Map<AppUserInformationDTO>(model.UserInformation);
        var result = await _appUserService.CreateAsync(appUserInformationDto);
        if (result.IsSuccess)
        {
            return RedirectToAction("Index", "Home");

        }
        return View(model);
    }
    public IActionResult GetOffer()
    {
        return View("GetOffer");
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }

}

IK_Project.UI/ViewComponents/AdminViewComponent.cs
using AutoMapper;
using IK_Project.Application.Services.AdminSevice;
using IK_Project.Domain.Entities.Concrete;
using IK_Project.UI.Areas.Admin.Models.ViewModels.AdminVM;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;

namespace IK_Project.UI.ViewComponents
{
	public class AdminViewComponent : ViewComponent
	{
		IAdminService _adminService;
		IMapper _mapper;
		private readonly SignInManager<AppUser> _signInManager;
		private readonly UserManager<AppUser> _userManager;




		public AdminViewComponent(IAdminService adminService, IMapper mapper, SignInManager<AppUser> signInManager, UserManager<AppUser> userManager)
		{
			_adminService = adminService;
			_mapper = mapper;
			_signInManager = signInManager;
			_userManager = userManager;

		}
		public async Task<IViewComponentResult> InvokeAsync()
		{
			//List<AdminListVM> adminVm = _mapper.Map<List<AdminListVM>>(await _adminService.GetDefaults(x => x.AppUser.UserName == userName));



			//var admin = adminVm.FirstOrDefault();
			////eklenecek unutma!!

			if (_signInManager.IsSignedIn(HttpContext.User))
			{

				//List<AdminListVM> adminVm = _mapper.Map<List<AdminListVM>>(await _adminService.GetDefaults(x => x.AppUser.UserName == HttpContext.User.Identity.Name));

				//var admin = adminVm.FirstOrDefault();


				return View(/*admin*/);
			}
			else
			{
				return View();






			}







		}
	}
}

IK_Project.UI/Areas/Admin/Views/Home/ChangePassword.cshtml
@model IK_Project.UI.Areas.Admin.Models.ViewModels.UserVMs.ChangePasswordVM

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Corona Admin</title>
    <link rel="stylesheet" href="../../assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="../../assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="../../assets/css/style.css">
    <link rel="shortcut icon" href="../../assets/images/favicon.png" />
</head>
<h2>Change Password</h2>

<form asp-action="ChangePassword" method="post">
    <!-- Old Password input -->
    <div class="form-outline mb-4">
        <label style="font-size:16px;" for="OldPassword">Old Password</label>
        <input style="font-size:16px;" asp-for="OldPassword" id="OldPassword" type="password" class="form-control" />
        <span asp-validation-for="OldPassword" class="text-danger"></span>

    </div>

    <!-- New Password input -->
    <div class="form-outline mb-4">
        <label style="font-size:16px;" for="NewPassword">New Password</label>
        <input style="font-size:16px;" asp-for="NewPassword" id="NewPassword" type="password" class="form-control" />
        <span asp-validation-for="NewPassword" class="text-danger"></span>
    </div>

    <!-- Confirm Password input -->
    <div class="form-outline mb-4">
        <label style="font-size:16px;" for="ConfirmPassword">Confirm Password</label>
        <input style="font-size:16px;" asp-for="ConfirmPassword" id="ConfirmPassword" type="password" class="form-control" />
        <span asp-validation-for="ConfirmPassword" class="text-danger"></span>
    </div>
    @using (Html.BeginForm("ChangePassword", "Account", FormMethod.Post))

    {
        <!--Kendi Site keyinizle değiştirin.-->
        <div class="g-recaptcha" data-sitekey="6LchLDAoAAAAAOed9VkYNeO4qaoJu_dPMUpawsiF"></div>
        <div> @TempData["Message"]</div>
        <input type="submit" value="ChangePassword" class="btn btn-primary" />


    }

    @*  <button type="submit" class="btn btn-block btn-primary">Change Password</button> *@
    @if (!string.IsNullOrEmpty(ViewData["OldPasswordError"] as string))
    {
        <div class="text-danger">@ViewData["OldPasswordError"]</div>
    }
</form>
<script src="https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit" async defer></script>
<script src="https://www.google.com/recaptcha/api.js"></script>

IK_Project.UI/Areas/Admin/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
    //Layout = "~Views/Shared/_Layout.cshtml";
}
<head>
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Corona Admin</title>
        <link rel="stylesheet" href="../../assets/vendors/mdi/css/materialdesignicons.min.css">
        <link rel="stylesheet" href="../../assets/vendors/css/vendor.bundle.base.css">
        <link rel="stylesheet" href="../../assets/css/style.css">
        <link rel="shortcut icon" href="../../assets/images/favicon.png" />
    </head>
</head>
<style>
    .container3 {
        display: flex;
        flex-direction: row;
        flex-wrap: wrap;
        justify-content: space-between;
        background-color: white;
        /*        height: 250px;
             gap: 10px;   */
    }
</style>

<div class="container3">
    <div class="card" style="width: 25rem;">
        <img src="~/images/workCompany.png" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Companies</h5>
            <p class="card-body">Adding, deleting, updating and listing Expense are done in this section. </p>
        </div>
        <div class="card-footer">
            <a class="btn btn-block btn-danger" style="color:azure; font-size:larger" asp-action="Create" asp-area="Admin" asp-controller="Company">Create Company</a>
            <a class="btn btn-block btn-danger" style="color:azure; font-size:larger" asp-action="GetAllCompanies" asp-area="Admin" asp-controller="Company">List All Companies</a>
        </div>
    </div>
    <div class="card" style="width: 36rem;">
        <img src="~/images/workCompanyManagers.png" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Company Managers</h5>
            <p class="card-body">Adding, deleting, updating and listing Advance are done in this section. </p>
        </div>
        <div class="card-footer">
            <a class="btn btn-block btn-primary" style="color:azure; font-size:larger" asp-action="Create" asp-area="Admin" asp-controller="CompanyManager">Create Company Manager</a>
            <a class="btn btn-block btn-primary" style="color:azure; font-size:larger" asp-action="GetAllCompanyManagers" asp-area="Admin" asp-controller="CompanyManager">List All Company Managers</a>
        </div>
    </div>
    <div class="card" style="width: 24rem;">
        <img src="~/images/workPackage.png" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Packages</h5>
            <p class="card-body">Adding, deleting, updating and listing Permission are done in this section. </p>
        </div>
        <div class="card-footer">
            <a class="btn btn-block btn-success" style="color:azure; font-size:larger" asp-action="Create" asp-area="Admin" asp-controller="Menu">Create Package</a>
            <a class="btn btn-block btn-success" style="color:azure; font-size:larger" asp-action="GetAllMenus" asp-area="Admin" asp-controller="Menu">List All Packages</a>
        </div>
    </div>

</div>

@*<div class="container3">

    @await Component.InvokeAsync("Admin")

   <p>admin area</p>

</div>

<div class="container3">


    <div class="card" style="width: 18rem;">
        <img src="~/images/work3.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Admin</h5>
            <p class="card-body">Adding Admins are done in this section.</p>
        </div>
        <div class="card-footer">
            <a class="btn btn-block btn-success" style="color:azure; font-size:larger" asp-action="Create" asp-area="Admin" asp-controller="Admin">Click</a>
    </div>
    </div>

    <div class="card" style="width: 18rem;">
        <img src="~/images/work1.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Company</h5>
            <p class="card-body">Adding, deleting, updating and listing companies are done in this section.</p>
        </div>
        <div class="card-footer">
            <a class="btn btn-block btn-primary" style="color:azure; font-size:larger" asp-action="Index" asp-area="Admin" asp-controller="Company">Click</a>
        </div>
    </div>

    <div class="card" style="width: 18rem;">
        <img src="~/images/work2.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Company Manager</h5>
            <p class="card-body">Adding, deleting, updating and listing Company Managers are done in this section. </p>
        </div>
        <div class="card-footer">
            <a class="btn btn-block btn-success" style="color:azure; font-size:larger" asp-action="Index" asp-area="Admin" asp-controller="CompanyManager">Click</a>
        </div>
    </div>

    <div class="card" style="width: 18rem;">
        <img src="~/images/work3.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Package</h5>
            <p class="card-body">Adding, deleting, updating and listing package are done in this section. </p>
        </div>
      
        <div class="card-footer">
            <a class="btn btn-block btn-info" style="color:azure; font-size:larger" asp-action="Index" asp-area="Admin" asp-controller="Menu">Click</a>
        </div>
    </div>

    <div class="card" style="width: 18rem;">
        <img src="~/images/work4.jpg" class="card-img-top" alt="...">
        <div class="card-body">
            <h5 class="card-title">Role</h5>
            <p class="card-text">Deleting, updating and listing roles are done in this section. </p>
        </div>
        <div class="card-footer">
            <a class="btn btn-block btn-success" style="color:azure; font-size:larger" asp-action="Index" asp-area="Admin" asp-controller="Role">Click</a>
        </div>
    </div>
    <div class="card" style="width: 18rem;">
        <img src="~/images/work2.jpg" class="card-img-top" alt="...">
  <div class="card-body">
            <h5 class="card-title">User-Role</h5>
            <p class="card-text">Adding, deleting, updating and listing roles to the user are done here.</p> 
  </div>
        <div class="card-footer">
            <a class="btn btn-block btn-info" style="color:azure; font-size:larger" asp-action="ListUsers" asp-area="Admin" asp-controller="Role">Click</a>
        </div>
</div>
</div>*@

IK_Project.UI/Areas/Admin/Views/Home/PasswordReset.cshtml
@using IK_Project.UI.Models;

@{
    ViewData["Title"] = "PasswordReset";
}
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Corona Admin</title>
    <link rel="stylesheet" href="../../assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="../../assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="../../assets/css/style.css">
    <link rel="shortcut icon" href="../../assets/images/favicon.png" />
</head>
<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
<script src="~/lib/jquery-validate/jquery.validate.js"></script>
<script src="~/lib/jquery-validate/jquery.validate.min.js"></script>

@model ResetPasswordViewModel
@if (ViewBag.State == null)
{
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-xl-10">
            <div class="card rounded-3 text-black">
                <div class="row g-0">
                    <div class="card-body p-md-5 mx-md-4">
                        <div class="text-center">
                            <img src="~/images/solusan.png"
                             style="width: 300px;" alt="logo">
                            <h4 class="mt-1 mb-5 pb-1"></h4>
                        </div>

                        <form asp-action="PasswordReset" method="post">


                            <div class="form-outline mb-4">
                                <label class="form-label" for="form2Example11">Email:</label>
                                <input id="form2Example11" asp-for="Email" class="form-control"
                                   placeholder="Write your Email" />
                                   <span asp-validation-for="Email"></span>
                            </div>
                             <div class="text-center pt-1 mb-5 pb-1">
                            <input type="submit" class="btn btn-primary btn-block" value="Send me E-mail" />
                        </div>
                            
                        </form>

                    </div>
                </div>


            </div>
        </div>
    </div>
}

else
{
    if (ViewBag.State)
    {
        <div class="alert-success">Email sent for password request.</div>
    }
    else
    {
        <div class="alert-success">Your e-mail address is not registered in the system.</div>
    }
}

IK_Project.UI/Areas/Admin/Views/Home/UpdatePassword.cshtml
@*@using IK_Project.UI.Models;

@{
    ViewData["Title"] = "UpdatePassword";
}

<script src="~/lib/jquery/dist/jquery.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.min.js"></script>
<script src="~/lib/jquery-validation-unobtrusive/jquery.validate.unobtrusive.js"></script>
<script src="~/lib/jquery-validate/jquery.validate.js"></script>
<script src="~/lib/jquery-validate/jquery.validate.min.js"></script>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Corona Admin</title>
    <link rel="stylesheet" href="../../assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="../../assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="../../assets/css/style.css">
    <link rel="shortcut icon" href="../../assets/images/favicon.png" />
</head>
@model UpdatePasswordViewModel
@if (ViewBag.State == null)
{
    <div class="row d-flex justify-content-center align-items-center h-100">
        <div class="col-xl-10">
            <div class="card rounded-3 text-black">
                <div class="row g-0">
                    <div class="card-body p-md-5 mx-md-4">
                        <div class="text-center">
                            <img src="~/images/solusan.png"
                             style="width: 300px;" alt="logo">
                            <h4 class="mt-1 mb-5 pb-1"></h4>
                        </div>

                        <form asp-action="UpdatePassword" method="post">


                            <div class="form-outline mb-4">
                                <label class="form-label" for="form2Example11">Password:</label>
                                <input id="form2Example11" asp-for="Password" class="form-control"
                                   placeholder="New password" />
                                <span asp-validation-for="Password"></span>
                            </div>
                            <div class="text-center pt-1 mb-5 pb-1">
                                <input type="submit" class="btn btn-primary btn-block" value="Update my password" />
                            </div>

                        </form>

                    </div>
                </div>


            </div>
        </div>
    </div>
}

else
{
    if (ViewBag.State)
    {
        <div class="alert-success" style="font-size:large">The password has been successfully updated.</div>
        <br />
        <br />
        <br />
        <div>
            <a class="btn btn-primary" style="font-size:large" asp-action="Login" asp-controller="Home">Please login with your new password</a>
        </div>
    }
    else
    {
        <div class="alert-success">Sorry, password update failed.</div>
    }
}

*@