IK_Project.UI/Areas/Admin/Controllers/CompanyController.cs
using AutoMapper;
using Humanizer;
using IK_Project.Application.Models.DTOs.CompanyDTOs;
using IK_Project.Application.Models.DTOs.CompanyManagerDTOs;
using IK_Project.Application.Services.CompanyService;
using IK_Project.Application.Services.MenuService;
using IK_Project.Domain.Entities.Concrete;
using IK_Project.Domain.Enums;
using IK_Project.Domain.Utilities.Interfaces;
using IK_Project.UI.Areas.Admin.Models.ViewModels.CompanyManagerVMs;
using IK_Project.UI.Areas.Admin.Models.ViewModels.CompanyVM;
using IK_Project.UI.FluentValidations.AdminAreaValidator.CompanyValidator;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using System.Data;

namespace IK_Project.UI.Areas.Admin.Controllers
{

    public class CompanyController : AdminBaseController
    {
        private readonly ICompanyService _companyService;
        private readonly IMapper _mapper;
        //private readonly IAppUserService _appUserService;
        IWebHostEnvironment _webHostEnvironment;
        private readonly IMenuService _menuService;

        public CompanyController(ICompanyService companyService, IMapper mapper, IWebHostEnvironment webHostEnvironment, IMenuService menuService)
        {
            _companyService = companyService;
            _mapper = mapper;
            _webHostEnvironment = webHostEnvironment;
            _menuService = menuService;

        }

        public IActionResult Index()
        {
            return View();
        }


        //Aktif ve Aktif olmayan Company Listeleme
        public async Task<IActionResult> GetAllActiveAndDeactiveCompanies()
        {
            var result = await _companyService.GetDefaults(x => x.IsActive == true || x.IsActive == false);
            if (result.Data == null)
            {
                return View();
            }
            var listVM = _mapper.Map<List<AdminCompanyListVM>>(result.Data);

            return View(listVM);
        }
        public async Task<IActionResult> GetAllCompanies()
        {
            var result = await _companyService.AllCompanies();
            if (result.Data==null)
            {
                return View();
            }
            List<AdminCompanyListVM> companyList = _mapper.Map<List<AdminCompanyListVM>>(result.Data);
            return View(companyList);


        }

        //Company Ekleme
        [HttpGet]
        public async Task<IActionResult> Create()
        {
            AdminCompanyCreateVM createVm = new AdminCompanyCreateVM()
            {
                MenuList = await GetMenuSelectListAsync(),
            };

            return View(createVm);

        }

        [HttpPost]
        public async Task<IActionResult> Create(AdminCompanyCreateVM vm)
        {
            if (ModelState.IsValid)
            {
                var menu = await _menuService.GetById(vm.MenuId);
                vm.DealEndDate = vm.DealStartDate.AddMonths(menu.Data.Period);
                var dto = _mapper.Map<CompanyCreateDTO>(vm);
                if (vm.LogoFile != null)
                {
                    string savedFilePath = await vm.LogoFile.SaveFileAsync(_webHostEnvironment.WebRootPath, "images");
                    dto.Logo = savedFilePath;
                }
                var result = await _companyService.Create(dto);
                if (result.IsSuccess)
                {
                    return RedirectToAction("GetAllCompanies");

                }


            }
            vm.MenuList = await GetMenuSelectListAsync();

            return View(vm);
        }
        

        //Toggle Active DeActive
        //[HttpGet]
        //public async Task<IActionResult> ActiveDeActive(int id)
        //{
        //    if (id == null)
        //    {
        //        return NotFound();
        //    }
        //    else
        //    {
        //        CompanyUpdateVM company = _mapper.Map<CompanyUpdateVM>(await _companyService.GetById(id));

        //        return View(ActiveDeActive(company));
        //    }
        //}
        //[HttpPost]
        //public async Task<IActionResult> ActiveDeActive(CompanyUpdateVM vm)
        //{

        //    try
        //    {
        //        var editDto = _mapper.Map<CompanyUpdateDTO>(vm);
        //        await _companyService.Edit(editDto);
        //        return RedirectToAction("GetAllActiveAndDeactiveCompanies");
        //    }
        //    catch (Exception ex)
        //    {
        //        TempData["error"] = ex.Message;
        //        return RedirectToAction("GetAllActiveAndDeactiveCompanies");
        //    }
        //}

        //Delete
        public async Task<IActionResult> Delete(Guid id)
        {
            try
            {
                await _companyService.Remove(id);
                return RedirectToAction("GetAllCompanies");
            }
            catch (Exception ex)
            {
                TempData["error"] = ex.Message;
                return RedirectToAction("GetAllCompanies");
            }
        }

        //  Category/Details/

        [HttpGet]
        public async Task<IActionResult> Details(Guid id)
        {
            if (id == null)
            {
                return NotFound();
            }
            else
            {
                var companyDto = await _companyService.GetById(id);
                AdminCompanyUpdateVM company = _mapper.Map<AdminCompanyUpdateVM>(companyDto.Data);
                company.MenuList = await GetMenuSelectListAsync();

                return View(company);
            }
        }

        [HttpPost]
        public async Task<IActionResult> Details(AdminCompanyUpdateVM vm)
        {
            if (!ModelState.IsValid)
            {
                vm.MenuList = await GetMenuSelectListAsync();

                return View(vm);

            }
            
            var menu = await _menuService.GetById(vm.MenuId);
            vm.DealEndDate = vm.DealStartDate.AddMonths(menu.Data.Period);
            var editDto = _mapper.Map<CompanyUpdateDTO>(vm);
            if (vm.LogoFile != null)
            {
              
                string savedFilePath = await vm.LogoFile.SaveFileAsync(_webHostEnvironment.WebRootPath, "images");

                editDto.Logo = savedFilePath;
            }
            await _companyService.Edit(editDto);
            return RedirectToAction("GetAllCompanies");
        }

        private async Task<SelectList> GetMenuSelectListAsync()
        {
            var menus = await _menuService.AllMenus();
            if (menus.Data != null)
            {
                return new SelectList(menus.Data.Select(x => new SelectListItem
                {
                    Value = x.Id.ToString(),
                    Text = x.Name,
                }), "Value", "Text");
            }
            else
            {
                // menus.Data null ise uygun bir SelectList oluşturun veya hata işleme stratejisi uygulayın.
                return new SelectList(Enumerable.Empty<SelectListItem>()); // Varsayılan boş SelectList örneği
            }

        }
        [HttpPost]
        public async Task<IActionResult> UpdateCompanyStatus(Guid companyId, bool newStatus)
        {

            var companyupdatedto = await _companyService.GetById(companyId);

            //companyupdatedto.Data.IsActive = newStatus;

            await _companyService.EditToggle(companyupdatedto.Data, newStatus);
            return View();
        }


    }
}

IK_Project.UI/Areas/CompanyManager/Controllers/ExpenseController.cs
using AutoMapper;
using IK_Project.Application.Models.DTOs.AdvanceDTOs;
using IK_Project.Application.Models.DTOs.CompanyDTOs;
using IK_Project.Application.Models.DTOs.DepartmantManagerDTOs;
using IK_Project.Application.Models.DTOs.EmployeeDTOs;
using IK_Project.Application.Models.DTOs.ExpenseDTOs;
using IK_Project.Application.Services.AccountService;
using IK_Project.Application.Services.CompanyManagerService;
using IK_Project.Application.Services.CompanyService;
using IK_Project.Application.Services.DepartmantManagerService;
using IK_Project.Application.Services.DepartmantService;
using IK_Project.Application.Services.EmployeeService;
using IK_Project.Application.Services.ExpenseService;
using IK_Project.Domain.Entities.Concrete;
using IK_Project.Domain.Enums;
using IK_Project.UI.Areas.Admin.Models.ViewModels.CompanyVM;
using IK_Project.UI.Areas.CompanyManager.Models;
using IK_Project.UI.Areas.CompanyManager.Models.AdvanceVM;
using IK_Project.UI.Areas.CompanyManager.Models.Employee;
using IK_Project.UI.Areas.CompanyManager.Models.ExpenseVM;
using IK_Project.UI.Areas.Employee.Models.ExpenseVMs;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Data;

namespace IK_Project.UI.Areas.CompanyManager.Controllers
{
    public class ExpenseController : CompanyManagerBaseController

    {

        private readonly UserManager<IdentityUser> _userManager;
        private readonly IExpenseService _expenseService;
        private readonly IEmployeeService _employeeService;
        private readonly IWebHostEnvironment _webHostEnvironment;
        readonly private ICompanyManagerService _cmService;
        private readonly IAccountService _accountService;
        readonly private ICompanyService _companyService;
        readonly private IDepartmantService _departmantService;
        private readonly IDepartmantManagerService _departmantManagerService;
        IMapper _mapper;


        public ExpenseController(UserManager<IdentityUser> userManager, IExpenseService expenseService, IEmployeeService employeeService, IMapper mapper, IWebHostEnvironment webHostEnvironment, ICompanyManagerService cmService, IDepartmantManagerService departmantManagerService, ICompanyService companyService, IDepartmantService departmantService, IAccountService accountService)
        {
            _userManager = userManager;
            _expenseService = expenseService;
            _employeeService = employeeService;
            _mapper = mapper;
            _webHostEnvironment = webHostEnvironment;
            _cmService = cmService;
            _accountService = accountService;
            _departmantManagerService = departmantManagerService;
            _departmantService = departmantService;
            _companyService = companyService;
        }
        public IActionResult Index()
        {
            return View();
        }
        public async Task<IActionResult> CheckExpenseDemands()
        {
            List<CompanyManagerExpenseListVM> companyManagerExpenseListVM = new List<CompanyManagerExpenseListVM>();
            var expenses = await _expenseService.AllExpenses();
            if (!expenses.IsSuccess)
            {
                return View(companyManagerExpenseListVM);
            }
            var user = await _accountService.GetUserAsync(User);
            var companyManager = await _cmService.GetAsync(user.Id);
            var company = await _companyService.GetCompany(x => x.CompanyManagerId == companyManager.Data.Id);
            var departmants = await _departmantService.GetDefaults(x => x.CompanyId == company.Data.Id);
            var departmantManagers = await _departmantManagerService.AllActiveManagers();
            var employees = await _employeeService.AllActiveEmployees();
            List<DepartmantManagerListDTO> CompanyDepartmantManagers = new List<DepartmantManagerListDTO>();
            if (departmants.Data != null && departmantManagers.Data != null)
            {
                foreach (var departmant in departmants.Data)
                {
                    foreach (var departmanManager in departmantManagers.Data)
                    {
                        if (departmanManager.Id == departmant.DepartmantManagerId)
                        {
                            departmanManager.DepartmantName = departmant.Name;
                            CompanyDepartmantManagers.Add(departmanManager);
                        }
                    }
                }
                List<EmployeeListDTO> listEmployee = new List<EmployeeListDTO>();
                if (employees.Data != null)
                {
                    foreach (var departmant in departmants.Data)
                    {
                        foreach (var employee in employees.Data)
                        {
                            if (employee.DepartmantId == departmant.Id)
                            {
                                employee.DepartmantName = departmant.Name;
                                listEmployee.Add(employee);
                            }
                        }
                    }
                    List<ExpenseListDTO> expenseListDTOs = new List<ExpenseListDTO>();
                    if (listEmployee != null)
                    {
                        foreach (var employee in listEmployee)
                        {
                            foreach (var expence in expenses.Data)
                            {
                                if (employee.Id == expence.EmployeeId)
                                {
                                    expence.EmployeeName = $"{employee.Name} {employee.LastName}";
                                    expenseListDTOs.Add(expence);
                                }

                            }
                        }
                    }
                    if (CompanyDepartmantManagers != null)
                    {
                        foreach (var CompanyDepartmantManager in CompanyDepartmantManagers)
                        {
                            foreach (var expence in expenses.Data)
                            {
                                if (CompanyDepartmantManager.Id == expence.DepartmantManagerId)
                                {
                                    expence.EmployeeName = $"{CompanyDepartmantManager.Name} {CompanyDepartmantManager.LastName}";
                                    expenseListDTOs.Add(expence);
                                }
                            }
                        }
                    }
                    companyManagerExpenseListVM = _mapper.Map<List<CompanyManagerExpenseListVM>>(expenseListDTOs);
                    return View(companyManagerExpenseListVM);
                }
            }
            return View(companyManagerExpenseListVM);
        }
        public async Task<IActionResult> Aprove(Guid Id)
        {
            var result = await _expenseService.GetById(Id);
            if (!result.IsSuccess)
            {
                return View();
            }
            result.Data.ConfirmationStatus = Domain.Enums.ConfirmationStatus.Confirm;
            await _expenseService.Edit(result.Data);
            return RedirectToAction("CheckExpenseDemands");
        }
        public async Task<IActionResult> Reject(Guid Id)
        {
            var result = await _expenseService.GetById(Id);
            if (!result.IsSuccess)
            {
                return View();
            }
            result.Data.ConfirmationStatus = Domain.Enums.ConfirmationStatus.Reject;
            await _expenseService.Edit(result.Data);
            return RedirectToAction("CheckExpenseDemands");
        }
    }
}

IK_Project.UI/Areas/DepartmantManager/Views/Expense/GetAllExpense.cshtml
@using IK_Project.UI.Areas.DepartmantManager.Models.DepartmantManagerExpenseVMs;

@{
    ViewData["Title"] = "GetAllExpenses";
}

@model List<DepartmantManagerExpenseListVM>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Corona Admin</title>
    <link rel="stylesheet" href="../../assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="../../assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="../../assets/css/style.css">
    <link rel="shortcut icon" href="../../assets/images/favicon.png" />
</head>
<div class="row">
</div>

<br />
<div class="row">
    <div class="col-lg-12">
        <table class="table align-middle mb-0 bg-white">
            <thead class="bg-light">
                <tr>
                    <th>Employee Name</th>
                    <th>Expense Type</th>
                    <th>Amount</th>
                    <th>Currency Unit</th>
                    <th>Confirmation Status</th>
                    @*   <th>Date of Reply</th>
                     <th>Reason Of Rejection</th> *@
                    <th>Confirm</th>
                    <th>Reject</th>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.EmployeeName">@item.EmployeeName</p>
                            <p class="text-muted mb-0"></p>
                        </td>
                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.ExpenseType">@item.ExpenseType</p>
                            <p class="text-muted mb-0"></p>
                        </td>
                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.Amount">@item.Amount</p>
                            <p class="text-muted mb-0"></p>
                        </td>
                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.CurrencyUnit">@item.CurrencyUnit</p>
                            <p class="text-muted mb-0"></p>
                        </td>
                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.ConfirmationStatus">@item.ConfirmationStatus</p>
                            <p class="text-muted mb-0"></p>
                        </td>
                        @*  @if (item.DateOfReply != null)
                        {
                            <td>
                                <p class="fw-normal mb-1" asp-for="@item.DateOfReply">@item.DateOfReply.Value.ToShortDateString()</p>
                            </td>
                        }
                            @if (item.ReasonOfRejection != null)
                    {
                    <td>
                    <p class="fw-normal mb-1" asp-for="@item.ReasonOfRejection">@item.ReasonOfRejection</p>
                    </td>
                    } *@
                        <td>
                            <a asp-action="Aprove" asp-area="DepartmantManager" asp-controller="Expense" asp-route-id="@item.Id" type="button" class="btn btn-success">
                                Confirm
                            </a>
                        </td>
                        <td>
                            <a asp-action="Reject" asp-area="DepartmantManager" asp-controller="Expense" asp-route-id="@item.Id" type="button" class="btn btn-danger">
                                Reject
                            </a>
                        </td>
                        @*    <td>
                    <a asp-action="Details" asp-area="Admin" asp-controller="Company" asp-route-id="@item.Id" type="button" class="btn btn-info">
                    Detail
                    </a>
                    </td>*@
                        @*   <td>
                    <a asp-action="Delete" asp-area="Admin" asp-controller="Company" asp-route-id="@item.Id" type="button" class="btn btn-danger" onclick="return showDataAlert()">
                    Delete
                    </a>
                    </td>
                    *@
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

IK_Project.UI/Areas/DepartmantManager/Views/Expense/GetExenseDM.cshtml
@using IK_Project.UI.Areas.DepartmantManager.Models.DepartmantManagerExpenseVMs;

@{
    ViewData["Title"] = "GetExpenseDM";
}

@model List<DepartmantManagerExpenseListVM>
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Corona Admin</title>
    <link rel="stylesheet" href="../../assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="../../assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="../../assets/css/style.css">
    <link rel="shortcut icon" href="../../assets/images/favicon.png" />
</head>
<div class="row">
</div>

<br />
<div class="row">
    <div class="col-lg-12">
        <table class="table align-middle mb-0 bg-white">
            <thead class="bg-light">
                <tr>
                    <th>Expense Type</th>
                    <th>Amount</th>
                    <th>Currency Unit</th>
                    <th>Confirmation Status</th>
                    @* <th>Date of Reply</th>
                      <th>Reason Of Rejection</th> *@
                    <th>Detail</th>
                    <th>Delete</th>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr>
                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.ExpenseType">@item.ExpenseType</p>
                            <p class="text-muted mb-0"></p>
                        </td>
                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.Amount">@item.Amount</p>
                            <p class="text-muted mb-0"></p>
                        </td>
                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.CurrencyUnit">@item.CurrencyUnit</p>
                            <p class="text-muted mb-0"></p>
                        </td>
                        <td>
                            <p class="fw-normal mb-1" asp-for="@item.ConfirmationStatus">@item.ConfirmationStatus</p>
                            <p class="text-muted mb-0"></p>
                        </td>
                        @*  @if (item.DateOfReply != null)
                        {
                            <td>
                                <p class="fw-normal mb-1" asp-for="@item.DateOfReply">@item.DateOfReply.Value.ToShortDateString()</p>
                            </td>
                        }
                             @if (item.ReasonOfRejection != null)
                    {
                    <td>
                    <p class="fw-normal mb-1" asp-for="@item.ReasonOfRejection">@item.ReasonOfRejection</p>
                    </td>
                    } *@
                        <td>
                            <a asp-action="Update" asp-area="DepartmantManager" asp-controller="Expense" asp-route-id="@item.Id" type="button" class="btn btn-success">
                                Update
                            </a>
                        </td>
                        <td>
                            <a asp-action="Update" asp-area="DepartmantManager" asp-controller="Expense" asp-route-id="@item.Id" type="button" class="btn btn-danger">
                                Delete
                            </a>
                        </td>
                        @*    <td>
                    <a asp-action="Details" asp-area="Admin" asp-controller="Company" asp-route-id="@item.Id" type="button" class="btn btn-info">
                    Detail
                    </a>
                    </td>*@
                        @*   <td>
                    <a asp-action="Delete" asp-area="Admin" asp-controller="Company" asp-route-id="@item.Id" type="button" class="btn btn-danger" onclick="return showDataAlert()">
                    Delete
                    </a>
                    </td>
                    *@
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

IK_Project.UI/Areas/DepartmantManager/Views/Expense/Update.cshtml
@using IK_Project.UI.Areas.DepartmantManager.Models.DepartmantManagerExpenseVMs;
@using IK_Project.Domain.Enums;

@model DepartmantManagerExpenseUpdateVm
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title> Corona Admin</title>
    <link rel="stylesheet" href="~/assets/vendors/mdi/css/materialdesignicons.min.css">
    <link rel="stylesheet" href="~/assets/vendors/css/vendor.bundle.base.css">
    <link rel="stylesheet" href="~/assets/css/style.css">
    <link rel="shortcut icon" href="~/assets/images/favicon.png" />
</head>
<style>


    body {
        margin-top: 20px;
        background-color: #f2f6fc;
        color: #69707a;
    }

    .img-account-profile {
        height: 10rem;
    }

    .rounded-circle {
        border-radius: 50% !important;
    }

    .card {
        box-shadow: 0 0.15rem 1.75rem 0 rgb(33 40 50 / 15%);
    }

        .card .card-header {
            font-weight: 500;
        }

    .card-header:first-child {
        border-radius: 0.35rem 0.35rem 0 0;
    }

    .card-header {
        padding: 1rem 1.35rem;
        margin-bottom: 0;
        background-color: rgba(33, 40, 50, 0.03);
        border-bottom: 1px solid rgba(33, 40, 50, 0.125);
    }

    .form-control, .dataTable-input {
        display: block;
        width: 100%;
        padding: 0.875rem 1.125rem;
        font-size: 0.875rem;
        font-weight: 400;
        line-height: 1;
        color: #69707a;
        background-color: #fff;
        background-clip: padding-box;
        border: 1px solid #c5ccd6;
        -webkit-appearance: none;
        -moz-appearance: none;
        appearance: none;
        border-radius: 0.35rem;
        transition: border-color 0.15s ease-in-out, box-shadow 0.15s ease-in-out;
    }

    .nav-borders .nav-link.active {
        color: #0061f2;
        border-bottom-color: #0061f2;
    }

    .nav-borders .nav-link {
        color: #69707a;
        border-bottom-width: 0.125rem;
        border-bottom-style: solid;
        border-bottom-color: transparent;
        padding-top: 0.5rem;
        padding-bottom: 0.5rem;
        padding-left: 0;
        padding-right: 0;
        margin-left: 1rem;
        margin-right: 1rem;
    }

    */
    .alert {
        padding: 20px;
        background-color: #f44336;
        color: white;
    }

    .closebtn {
        margin-left: 15px;
        color: white;
        font-weight: bold;
        float: right;
        font-size: 22px;
        line-height: 20px;
        cursor: pointer;
        transition: 0.3s;
    }

        .closebtn:hover {
            color: black;
        }

    body {
        font-family: Arial, Helvetica, sans-serif;
    }

    * {
        box-sizing: border-box;
    }

    input[type=text], select, textarea {
        width: 100%;
        padding: 12px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-top: 6px;
        margin-bottom: 16px;
        resize: vertical;
    }

    input[type=number], select, textarea {
        width: 100%;
        padding: 12px;
        border: 1px solid #ccc;
        border-radius: 4px;
        box-sizing: border-box;
        margin-top: 6px;
        margin-bottom: 16px;
        resize: vertical;
    }

    input[type=submit] {
        background-color: #04AA6D;
        color: white;
        padding: 12px 20px;
        border: none;
        border-radius: 4px;
        cursor: pointer;
    }

        input[type=submit]:hover {
            background-color: #45a049;
        }

    /.container {
        border-radius: 5px;
        background-color: transparent;
        padding: 10px;
    }

</style>
<div class="container-xl px-4 mt-4">

    <form enctype="multipart/form-data" method="post" asp-action="Update" asp-area="DepartmantManager" asp-controller="Expense">
        <div class="card mb-4 mb-xl-0">
            <div class="card-header" style="font-size:20px;">Expense Details</div>
            <div class="card-body">
                <div class="mb-3">
                    <label asp-for="Amount" style="font-size:16px;" class="small mb-1" for="form4Example1">Amount:</label>
                    <input style="font-size:16px;" asp-for="Amount" type="number" max="1000000" id="form4Example1" />
                    <span asp-validation-for="Amount" class="text-danger"></span>
                </div>
                <div class="mb-3">
                    <label style="font-size:16px;" for="form4Example1" asp-for="CurrencyUnit" class="small mb-1">Currency Unit:</label>
                    <select style="font-size:16px;" style="height:max-content" asp-for="CurrencyUnit" asp-items="@Html.GetEnumSelectList<CurrecyUnit>()"></select>
                </div>
                <div class="mb-3">
                    <label style="font-size:16px;" class="small mb-1" for="form4Example1">Created Date:</label>
                    <input type="date" value="" asp-for="CreatedDate" id="form4Example1" class="form-control" value="@Model.CreatedDate?.ToString("yyyy-MM-dd")" />
                </div>
@*                <div class="mb-3">
                    <label style="font-size:16px;" class="small mb-1" for="form4Example1">Date Of Reply:</label>
                    <input type="date" value="" asp-for="DateOfReply" id="form4Example1" class="form-control" value="@Model.DateOfReply?.ToString("yyyy-MM-dd")" />
                    <span asp-validation-for="DateOfReply" class="text-danger"></span>
                </div>*@
                <div class="mb-3">
                    <label hidden class="small mb-1" for="form4Example1">DepartmantManager:</label>
                    <input hidden readonly asp-for="DepartmantManagerId" id="form4Example1" class="form-control" />
                </div>
                <button type="submit" style="font-size:16px;" class="btn btn-primary float-right">Send Advance Demand</button>
            </div>
        </div>
    </form>
</div>